# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

brew:
  # Name template of the recipe
  # Default to project name
  name: vault-shared-users

  # Repository to push the tap to.
  github:
    owner: dollarshaveclub
    name: homebrew-tap

  # Template for the url.
  # Default is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  #url_template: "http://github.mycompany.com/foo/bar/releases/{{ .Tag }}/{{ .ArtifactName }}"

  # Allows you to set a custom download strategy.
  # Default is empty.
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  # Allows you to add a custom require_relative at the top of the formula template
  # Default is empty
  #custom_require: custom_download_strategy 

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: goreleaserbot
    email: goreleaser@dollarshaveclub.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Caveats for the user of your binary.
  # Default is empty.
  #caveats: "How to use this binary"

  # Your app's homepage.
  # Default is empty.
  #homepage: "https://example.com/"

  # Your app's description.
  # Default is empty.
  description: "Easily share users with 2FA access through Hashicorp Vault"

  # Setting this will prevent goreleaser to actually try to commit the updated
  # formula - instead, the formula file will be stored on the dist folder only,
  # leaving the responsibility of publishing it to the user.
  # Default is false.
  skip_upload: true

  # Custom block for brew.
  # Can be used to specify alternate downloads for devel or head releases.
  # Default is empty.
  #custom_block: |
  #  head "https://github.com/some/package.git"
  #  ...

  # Packages your package depends on.
  #dependencies:
  #  - git
  #  - zsh

  # Packages that conflict with your package.
  #conflicts:
  #  - svn
  #  - bash

  # Specify for packages that run as a service.
  # Default is empty.
  #plist: |
  #  <?xml version="1.0" encoding="UTF-8"?>
  #  ...

  # So you can `brew test` your formula.
  # Default is empty.
  #test: |
  #  system "#{bin}/program --version"
  #  ...

  # Custom install script for brew.
  # Default is 'bin.install "program"'.
  #install: |
  #  bin.install "program"
  #  ...